- name: Örnek SSH bağlantısı
  hosts: all
  tasks:
    - name: Hedef makinaya ping atma
      ping:

    - name: Paket listelerini güncelleme
      apt:
        update_cache: yes

    - name: Paketleri yükseltme
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
