---
- name: Örnek SSH bağlantısı
  hosts: all
  tasks:
    - name: Hedef makinaya ping atma
      ping:

    - name: Dosya oluşturma
      file:
        path: /tmp/ansible_test.txt
        state: touch

    - name: Metin dosyasına veri yazma
      copy:
        content: "Merhaba, bu bir test dosyasıdır."
        dest: /tmp/ansible_test.txt
