---
- name: SSH ile Java 17 LTS Kurulumu
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Hedef makinaya ping atma
      ping:

    - name: Paket listelerini güncelleme
      apt:
        update_cache: yes

    - name: Java 17 LTS yükle
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Java versiyonunu kontrol et
      command: java -version
      register: java_version_output

    - name: Kurulumun doğru olduğunu doğrula
      debug:
        msg: "{{ java_version_output.stdout }}"
